### ISSUE TITLE
animation fluency

### ISSUE THREAD

**Issue by choristery** [oleksandrbalan/pagecurl#16]
Hi, when I use `pagecurl`, it seems that the animation freezes on some devices because of the complex content. Do you have any good suggestions for this?

**Comment by oleksandrbalan** [comment]
Hi 👋

On which API levels do you register freezing? There are two differrnt implementation for API levels before 28 and

**Comment by choristery** [comment]
API levels is 33

**Comment by oleksandrbalan** [comment]
Uff, weird 😬

Could you please try to disable shadows by setting either alpha or radius to 0, to check if it is due to shadow or something else?
