### ISSUE TITLE
Page-turning effect

### ISSUE THREAD

**Issue by choristery** [oleksandrbalan/pagecurl#17]
Hi，I compared this app with other reading applications I've used so far, and I noticed that they have a page-turning effect that simulates the bending of real book pages. I hope you don't mind me asking, but is it easy to implement this effect?

- Image 1(other app)
![](https://i.postimg.cc/xjF90YYR/20230724084045.jpg)

- Image 2(page curl)
- ![](https://i.postimg.cc/t4zqG6g1/20230724084740.jpg)

**Comment by oleksandrbalan** [comment]
I have seen those bending effects before implementing PageCurl, and initially I wanted to achieve more 3D-ish visual, but failed. IMHO they are implemented via some sort of 3D engine (did not investigate it) to make smooth page curl, text bending and that soft shadows. Maybe it is possible with canvas API, but that would be hella more math 😅

**Comment by choristery** [comment]
Okay, I understand. Perhaps this library is helpful, but I'm quite unfamiliar with the related APIs.

https://github.com/FantasticPornTaiQiang/PTQFlipper
