### ISSUE TITLE
Regarding issues with animation.

### ISSUE THREAD

**Issue by choristery** [oleksandrbalan/pagecurl#28]
When I upgraded to Compose BOM 2024.02.00, the `pageCurlState.next()`/`prev()` calls ceased to have an effect. 

Note: In version 2024.01.00, there was an issue with `keyframes `in the animation-core. In version 2024.02.00, this problem has been fixed, and it is presumed to be related to the aforementioned issue.

**Comment by oleksandrbalan** [comment]
Yea, I was thinking to bump compose in 1.5.0, but there was only broken 2024.01.00 available.

What is weird that if I update lib to 2024.02.00 demo app works perfectly fine for me without any other changes 🤔 
I will release 1.5.1 with newer BOM today, so you could try if it works for you.

**Comment by oleksandrbalan** [comment]
Could you please check if 1.5.1 works for you?

**Comment by choristery** [comment]
Sry, during the recent Chinese New Year holiday, I have already resolved this issue through other means. It is not necessary to call `state.next` within the callback of `onCustomTap`.
